# Generated by Django 3.0.6 on 2020-06-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the vendor', max_length=200)),
                ('cnpj', models.CharField(help_text='Enter the CNPJ inlcude . / and -', max_length=18, unique=True, verbose_name='CNPJ')),
                ('city', models.CharField(help_text='Enter the City of the vendor', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(help_text='Enter the name of the product', max_length=50)),
                ('code', models.CharField(help_text='Enter the code of the product', max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Vendor')),
            ],
        ),
    ]
