# Generated by Django 3.0.6 on 2020-06-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='cnpj',
            field=models.CharField(help_text='Enter only numbers', max_length=14, unique=True, verbose_name='CNPJ'),
        ),
    ]
